on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - output.sarif
name: upload sarif
jobs:
  semgrep:
    name: upload-sarif
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    # - run: semgrep ci --code --secrets --sarif -o semgrep.sarif
    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: semgrep.sarif
    #     path: semgrep.sarif
    - name: Upload SARIF to GHAS Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: output.sarif
      if: always()
